#include "clearTerminal.c"
#include "arrayInsert.c"
#include "arrayRemove.c"
#include "multiplyMatrices.c"
#include "matchArrayValues.c"
#include "differenceOfSets.c"
#include "removeDuplicates.c"
#include "checkMatrixDensity.c"
#include "identityMatrix.c"
#include "arraysPointers.c"
#include "combineArrays.c"
#include "functionsPointers.c"
#include "memManageMalloc.c"
#include "sumInputCalloc.c"
#include "memManageRealloc.c"
#include "isPalindrome.c"
#include "firstRepeatCharInStr.c"
#include "charCountInStr.c"
#include "simpleRecursion.c"
#include "stringsPointersMemory.c"
#include "structs.c"
#include "typedefStructs.c"
#include "vowelsToUppercase.c"
#include "struct01.c"
#include "stringFlip.c"
#include "returnValues.c"
#include "recursiveLinkedList.c"
#include "recursionTest01.c"
#include "recursiveDiv.c"
#include "pointersArrayVals.c"
#include "loopLinkedList.c"
//#include "hexBinConvert.c"

void clearTerminal();
void arrayInsert();
void arrayRemove();
void multiplyMatrices();
void matchArrayValues();
void differenceOfSets();
void removeDuplicates();
void checkMatrixDensity();
void identityMatrix();
void arraysPointers();
void combineArrays();
void functionsPointers();
void memManagementMalloc();
void sumInputCalloc();
void memManageRealloc();
void isPalindrome();
void firstRepeatCharInStr();
void charCountInStr();
void runRecursion();
void stringsPointersMemory();
void structs();
void typedefStructs();
void vowelsToUppercase();
int struct01();
void stringFlip();
void returnValues();
int recursiveLinkedList();
int recursionTest();
void recursiveDiv();
void pointersArraysVals();
int loopLinkedList();
//void hexBinConvert();
